/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sunhx.exam;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", App.getScreenSize());
    }
}
